export const Maps = [
  {
    index: 0,
    abreviation: 'MKS',
    name: 'Champidrome',
    picture: '././assets/images/mks.png',
  },

  {
    index: 1,
    abreviation: 'WP',
    name: 'Parc Gloop Gloop',
    picture: '././assets/images/wp.png',
  },
  {
    index: 2,
    abreviation: 'SSC',
    name: 'Piste aux délices',
    picture: '././assets/images/ssc.png',
  },
  {
    index: 3,
    abreviation: 'TR',
    name: 'Temple Thwomp',
    picture: '././assets/images/tr.png',
  },
  {
    index: 4,
    abreviation: 'MC',
    name: 'Circuit Mario',
    picture: '././assets/images/mc.png',
  },
  {
    index: 5,
    abreviation: 'TH',
    name: 'Promenade Toad',
    picture: '././assets/images/th.png',
  },
  {
    index: 6,
    abreviation: 'TM',
    name: 'Manoir trempé',
    picture: '././assets/images/tm.png',
  },
  {
    index: 7,
    abreviation: 'SGF',
    name: 'Cascades Maskass',
    picture: '././assets/images/sgf.png',
  },
  {
    index: 8,
    abreviation: 'SA',
    name: 'Aéroport Azur',
    picture: '././assets/images/sa.png',
  },
  {
    index: 9,
    abreviation: 'DS',
    name: 'Lagon tourbillon',
    picture: '././assets/images/ds.png',
  },
  {
    index: 10,
    abreviation: 'Ed',
    name: 'Club Mario',
    picture: '././assets/images/ed.png',
  },
  {
    index: 11,
    abreviation: 'MW',
    name: 'Descente giclée',
    picture: '././assets/images/mw.png',
  },
  {
    index: 12,
    abreviation: 'CC',
    name: 'Voie céleste',
    picture: '././assets/images/cc.png',
  },
  {
    index: 13,
    abreviation: 'BDD',
    name: 'Désert Toussec',
    picture: '././assets/images/bdd.png',
  },
  {
    index: 14,
    abreviation: 'BC',
    name: 'Château de Bowser',
    picture: '././assets/images/bc.png',
  },
  {
    index: 15,
    abreviation: 'RR',
    name: 'Route Arc-en-ciel',
    picture: '././assets/images/rr.png',
  },
  {
    index: 16,
    abreviation: 'dYC',
    name: 'Circuit Yoshi',
    picture: '././assets/images/dyc.png',
  },
  {
    index: 17,
    abreviation: 'dEA',
    name: 'Arène Excitebike',
    picture: '././assets/images/dea.png',
  },
  {
    index: 18,
    abreviation: 'dDD',
    name: 'Route du dragon',
    picture: '././assets/images/ddd.png',
  },
  {
    index: 19,
    abreviation: 'dMC',
    name: 'Mute City',
    picture: '././assets/images/dmc.png',
  },
  {
    index: 20,
    abreviation: 'dWGM',
    name: 'Mine Wario',
    picture: '././assets/images/dwgm.png',
  },
  {
    index: 21,
    abreviation: 'dRR',
    name: 'Route Arc-en-ciel SNES',
    picture: '././assets/images/drr.png',
  },
  {
    index: 22,
    abreviation: 'dIIO',
    name: 'Station Glagla',
    picture: '././assets/images/diio.png',
  },
  {
    index: 23,
    abreviation: 'dHC',
    name: 'Circuit Hyrule',
    picture: '././assets/images/dhc.png',
  },
  {
    index: 24,
    abreviation: 'rMMM',
    name: 'Prairie Meuh-meuh',
    picture: '././assets/images/rmmm.png',
  },
  {
    index: 25,
    abreviation: 'rMC',
    name: 'Circuit Mario GBA',
    picture: '././assets/images/rmc.png',
  },
  {
    index: 26,
    abreviation: 'rCCB',
    name: 'Plage Cheep-cheep',
    picture: '././assets/images/rccb.png',
  },
  {
    index: 27,
    abreviation: 'rTT',
    name: 'Autoroute Toad',
    picture: '././assets/images/rtt.png',
  },
  {
    index: 28,
    abreviation: 'rDDD',
    name: 'Désert Sec-sec',
    picture: '././assets/images/rddd.png',
  },
  {
    index: 29,
    abreviation: 'rDP3',
    name: 'Plaine Donut 3',
    picture: '././assets/images/rdp3.png',
  },
  {
    index: 30,
    abreviation: 'rRRy',
    name: 'Autodrome royal',
    picture: '././assets/images/rrry.png',
  },
  {
    index: 31,
    abreviation: 'rDKJ',
    name: 'Forêt tropicale DK',
    picture: '././assets/images/rdkj.png',
  },
  {
    index: 32,
    abreviation: 'rWS',
    name: 'Stade Wario',
    picture: '././assets/images/rws.png',
  },
  {
    index: 33,
    abreviation: 'rSL',
    name: 'Royaume Sorbet',
    picture: '././assets/images/rsl.png',
  },
  {
    index: 34,
    abreviation: 'rMP',
    name: 'Piste musicale',
    picture: '././assets/images/rmp.png',
  },
  {
    index: 35,
    abreviation: 'rYV',
    name: 'Vallée Yoshi',
    picture: '././assets/images/ryv.png',
  },
  {
    index: 36,
    abreviation: 'rTTC',
    name: 'Horloge Tic-tac',
    picture: '././assets/images/rttc.png',
  },
  {
    index: 37,
    abreviation: 'rPPS',
    name: 'Egouts Piranha',
    picture: '././assets/images/rpps.png',
  },
  {
    index: 38,
    abreviation: 'rGV',
    name: 'Volcan grondant',
    picture: '././assets/images/rgv.png',
  },
  {
    index: 39,
    abreviation: 'rRRd',
    name: 'Route Arc-en-ciel N64',
    picture: '././assets/images/rrrd.png',
  },
  {
    index: 40,
    abreviation: 'dBP',
    name: 'Parc Baby',
    picture: '././assets/images/dbp.png',
  },
  {
    index: 41,
    abreviation: 'dCL',
    name: 'Pays fromage',
    picture: '././assets/images/dcl.png',
  },
  {
    index: 42,
    abreviation: 'dWW',
    name: 'Passage feuillage',
    picture: '././assets/images/dww.png',
  },
  {
    index: 43,
    abreviation: 'dAC',
    name: 'Animal Crossing',
    picture: '././assets/images/dac.png',
  },
  {
    index: 44,
    abreviation: 'dNBC',
    name: 'Koopapolis',
    picture: '././assets/images/dnbc.png',
  },
  {
    index: 45,
    abreviation: 'dRiR',
    name: 'Route ruban',
    picture: '././assets/images/drir.png',
  },
  {
    index: 46,
    abreviation: 'dSBS',
    name: 'Métro turbo',
    picture: '././assets/images/dsbs.png',
  },
  {
    index: 47,
    abreviation: 'dBB',
    name: 'Big Blue',
    picture: '././assets/images/dbb.png',
  },
  {
    index: 48,
    abreviation: 'bPP',
    name: 'Promenade à Paris',
    picture: '././assets/images/bpp.png',
  },
  {
    index: 49,
    abreviation: 'bTC',
    name: 'Circuit Toad',
    picture: '././assets/images/btc.png',
  },
  {
    index: 50,
    abreviation: 'bCMo',
    name: 'Montagne choco',
    picture: '././assets/images/bcmo.png',
  },
  {
    index: 51,
    abreviation: 'bCMa',
    name: 'Supermarché Coco',
    picture: '././assets/images/bcma.png',
  },
  {
    index: 52,
    abreviation: 'bTB',
    name: 'Traversée de Tokyo',
    picture: '././assets/images/btb.png',
  },
  {
    index: 53,
    abreviation: 'bSR',
    name: 'Corniche Champignon',
    picture: '././assets/images/bsr.png',
  },
  {
    index: 54,
    abreviation: 'bSG',
    name: 'Jardin volant',
    picture: '././assets/images/bsg.png',
  },
  {
    index: 55,
    abreviation: 'bNH',
    name: 'Dojo ninja',
    picture: '././assets/images/bnh.png',
  },
  {
    index: 56,
    abreviation: 'bNYM',
    name: 'Escapade new-yorkaise',
    picture: '././assets/images/bnym.png',
  },
  {
    index: 57,
    abreviation: 'bMC3',
    name: 'Circuit Mario 3',
    picture: '././assets/images/bmc3.png',
  },
  {
    index: 58,
    abreviation: 'bKD',
    name: 'Désert Kalimari',
    picture: '././assets/images/bkd.png',
  },
  {
    index: 59,
    abreviation: 'bWP',
    name: 'Flipper Waluigi',
    picture: '././assets/images/bwp.png',
  },
  {
    index: 60,
    abreviation: 'bSS',
    name: 'Sprint à Sydney',
    picture: '././assets/images/bss.png',
  },
  {
    index: 61,
    abreviation: 'bSL',
    name: 'Pays neigeux',
    picture: '././assets/images/bsl.png',
  },
  {
    index: 62,
    abreviation: 'bMG',
    name: 'Gorge Champignon',
    picture: '././assets/images/bmg.png',
  },
  {
    index: 63,
    abreviation: 'bSHS',
    name: 'Cité Sorbet',
    picture: '././assets/images/bshs.png',
  },
  {
    index: 64,
    abreviation: 'bLL',
    name: 'Détour à Londres',
    picture: '././assets/images/bll.png',
  },
  {
    index: 65,
    abreviation: 'bBL',
    name: 'Lac Boo',
    picture: '././assets/images/bbl.png',
  },
  {
    index: 66,
    abreviation: 'bRRM',
    name: 'Mont Eboulis',
    picture: '././assets/images/brrm.png',
  },
  {
    index: 67,
    abreviation: 'bMT',
    name: 'Bois vermeil',
    picture: '././assets/images/bmt.png',
  },
  {
    index: 68,
    abreviation: 'bBB',
    name: 'Balade berlinoise',
    picture: '././assets/images/bbb.png',
  },
  {
    index: 69,
    abreviation: 'bPG',
    name: 'Jardin Peach',
    picture: '././assets/images/bpg.png',
  },
  {
    index: 70,
    abreviation: 'bMM',
    name: 'Mont festif',
    picture: '././assets/images/bmm.png',
  },
  {
    index: 71,
    abreviation: 'bRR',
    name: 'Route Arc-en-ciel 3DS',
    picture: '././assets/images/brr.png',
  },
  {
    index: 72,
    abreviation: 'bAD',
    name: 'Virée à Amsterdam',
    picture: '././assets/images/bad.png',
  },
  {
    index: 73,
    abreviation: 'bRP',
    name: 'Riverside Parc',
    picture: '././assets/images/brp.png',
  },
  {
    index: 74,
    abreviation: 'bDKS',
    name: 'Pic DK',
    picture: '././assets/images/bdksc.png',
  },
  {
    index: 75,
    abreviation: 'bYI',
    name: 'Ile de Yoshi',
    picture: '././assets/images/byi.png',
  },
  {
    index: 76,
    abreviation: 'bBR',
    name: 'Bousculade à Bangkok',
    picture: '././assets/images/bbr.png',
  },
  {
    index: 77,
    abreviation: 'bMC',
    name: 'Circuit Mario DS',
    picture: '././assets/images/bmc.png',
  },
  {
    index: 78,
    abreviation: 'bWS',
    name: 'Stade Waluigi',
    picture: '././assets/images/bws.png',
  },
  {
    index: 79,
    abreviation: 'bSiS',
    name: 'Poursuite à Singapour',
    picture: '././assets/images/bsis.png',
  },
  {
    index: 80,
    abreviation: 'bAtD',
    name: 'Athènes antique',
    picture: '././assets/images/batd.png',
  },
  {
    index: 81,
    abreviation: 'bDC',
    name: 'Paquebot Daisy',
    picture: '././assets/images/bdc.png',
  },
  {
    index: 82,
    abreviation: 'bMH',
    name: 'Route Clair-de-lune',
    picture: '././assets/images/bmh.png',
  },
  {
    index: 83,
    abreviation: 'bScS',
    name: 'Course à la propreté',
    picture: '././assets/images/bscs.png',
  },
  {
    index: 84,
    abreviation: 'bLAL',
    name: 'Road-trip à Los Angeles',
    picture: '././assets/images/blal.png',
  },
  {
    index: 85,
    abreviation: 'bSW',
    name: 'Pays Crépuscule',
    picture: '././assets/images/bsw.png',
  },
  {
    index: 86,
    abreviation: 'bKC',
    name: 'Cap Koopa',
    picture: '././assets/images/bkc.png',
  },
  {
    index: 87,
    abreviation: 'bVV',
    name: 'Virages à Vancouver',
    picture: '././assets/images/bvv.png',
  },
  {
    index: 88,
    abreviation: 'bRA',
    name: 'Roma Romantica',
    picture: '././assets/images/bra.png',
  },
  {
    index: 89,
    abreviation: 'bDKM',
    name: 'Montagne DK',
    picture: '././assets/images/bdkm.png',
  },
  {
    index: 90,
    abreviation: 'bDCW',
    name: 'Circuit Daisy',
    picture: '././assets/images/bcdw.png',
  },
  {
    index: 91,
    abreviation: 'bPPC',
    name: 'Ruines Plante Piranha',
    picture: '././assets/images/bppc.png',
  },
  {
    index: 92,
    abreviation: 'bMD',
    name: 'Méandres madrilènes',
    picture: '././assets/images/bmd.png',
  },
  {
    index: 93,
    abreviation: 'bRIW',
    name: "Monde glacé d'Harmonie",
    picture: '././assets/images/briw.png',
  },
  {
    index: 94,
    abreviation: 'bBC3',
    name: 'Château de Bowser 3',
    picture: '././assets/images/bbc3.png',
  },
  {
    index: 95,
    abreviation: 'bRRW',
    name: 'Route Arc-en-ciel Wii',
    picture: '././assets/images/brrw.png',
  },
];
